export enum RootStacks {
	HomeTabs = 'HomeTabs',
	OnboardingStack = 'OnboardingStack',
}

export enum OnboardingScreens {
	Splash = 'Splash',
	Introduction = 'Introduction',
	AcknowledgingYourPast = 'AcknowledgingYourPast',
	WhatWouldILikeToLearn = 'WhatWouldILikeToLearn',
	HavingTheLovingCommunities = 'HavingTheLovingCommunities',
	WhenYouForget = 'WhenYouForget',
	TheScienceOfLove = 'TheScienceOfLove',
	MasteringLove = 'MasteringLove',
	FromComfort = 'FromComfort',
	Control = 'Control',
	TheJourneyStartsNow = 'TheJourneyStartsNow',
	SignupForm = 'SignupForm',
	ThankYouForSigningUp = 'ThankYouForSigningUp',
	LetTheAppTeachYou = 'LetTheAppTeachYou',
	Dependency = 'Dependency',
	LoveVsHeartburn = 'LoveVsHeartburn',
	NavigatingTheStructure = 'NavigatingTheStructure',
	BornToBeLoved = 'BornToBeLoved',
	SetYourAlertsIntro = 'SetYourAlertsIntro',
	SetYourAlerts = 'SetYourAlerts',
	SetYourAlertsThankYou = 'SetYourAlertsThankYou',
	HowCanITell = 'HowCanITell',
	NeffSurveyIntro = 'NeffSurveyIntro',
	NeffSurvey1 = 'NeffSurvey1',
	NeffSurvey2 = 'NeffSurvey2',
	NeffSurvey3 = 'NeffSurvey3',
	NeffSurvey4 = 'NeffSurvey4',
	NeffSurvey5 = 'NeffSurvey5',
	NeffSurvey6 = 'NeffSurvey6',
	NeffSurvey7 = 'NeffSurvey7',
	NeffSurvey8 = 'NeffSurvey8',
	NeffSurvey9 = 'NeffSurvey9',
	NeffSurvey10 = 'NeffSurvey10',
	NeffSurvey11 = 'NeffSurvey11',
	NeffSurvey12 = 'NeffSurvey12',
	NeffSurveyBreakdown = 'NeffSurveyBreakdown',
	NeffSurveyThankYou = 'NeffSurveyThankYou',
	NeffSurveyGoodJob = 'NeffSurveyGoodJob',
	EmotionalResetButton = 'EmotionalResetButton',
	FrustratedReadyToQuit = 'FrustratedReadyToQuit',
	FrustratedWithApp = 'FrustratedWithApp',
	FrustratedWithProgress = 'FrustratedWithProgress',
	BriefOverviewOfButtons = 'BriefOverviewOfButtons',
	AddYourContacts = 'AddYourContacts',
	YouAreReady = 'YouAreReady',
}

export enum TabNames {
	HomeScreen = 'Home',
	JournalScreen = 'Journal',
	FAQScreen = 'FAQ',
	ResetScreen = 'Emotional Reset',
}

export enum StepScreens {
	Home = 'Home',
	DayOverview = 'DayOverview',
	GoodJob = 'GoodJob',
	Step1Intention = 'Step1Intention',
	Step1Activities1 = 'Step1Activities1',
	Step1Activities2 = 'Step1Activities2',
	Step1Activities3 = 'Step1Activities3',
}
