export enum Course1Step1Screens {
	Home = 'course1_step1_home',
	DayOverview = 'course1_step1_day_overview',
	GoodJob = 'course1_step1_good_job',
	Intention = 'course1_step1_intention',
	Activities1 = 'course1_step1_activities1',
	Activities2 = 'course1_step1_activities2',
	Activities3 = 'course1_step1_activities3',
	Resources = 'course1_step1_resources',
	Survey = 'course1_step1_survey',
	Reflection = 'course1_step1_reflection',
	Visualization = 'course1_step1_visualization',
}

export enum Course1Step2Screens {
	Home = 'course1_step2_home',
	DayOverview = 'course1_step2_day_overview',
	GoodJob = 'course1_step2_good_job',
	Intention = 'course1_step2_intention',
	Activities1 = 'course1_step2_activities1',
	Activities1B = 'course1_step2_activities1b',
	Activities2 = 'course1_step2_activities2',
	Activities3 = 'course1_step2_activities3',
	Activities4 = 'course1_step2_activities4',
	Activities5 = 'course1_step2_activities5',
	Resources1 = 'course1_step2_resources1',
	Resources2 = 'course1_step2_resources2',
	Survey = 'course1_step2_survey',
	Reflection = 'course1_step2_reflection',
}

export enum Course1Step3Screens {
	Home = 'course1_step3_home',
	DayOverview = 'course1_step3_day_overview',
	GoodJob = 'course1_step3_good_job',
	Intention = 'course1_step3_intention',
	Activities1 = 'course1_step3_activities1',
	Activities2 = 'course1_step3_activities2',
	Activities3 = 'course1_step3_activities3',
	Activities4 = 'course1_step3_activities4',
	Resources = 'course1_step3_resources',
	Survey = 'course1_step3_survey',
	Reflection = 'course1_step3_reflection',
}

export enum Course1Step4Screens {
	Home = 'course1_step4_home',
	DayOverview = 'course1_step4_day_overview',
	GoodJob = 'course1_step4_good_job',
	Intention = 'course1_step4_intention',
	Activities1 = 'course1_step4_activities1',
	Activities2 = 'course1_step4_activities2',
	Activities3 = 'course1_step4_activities3',
	Activities4 = 'course1_step4_activities4',
	Resources1 = 'course1_step4_resources1',
	Resources2 = 'course1_step4_resources2',
	Resources3 = 'course1_step4_resources3',
	Survey = 'course1_step4_survey',
	Reflection = 'course1_step4_reflection',
}

export enum Course1Step5Screens {
	Home = 'course1_step5_home',
	DayOverview = 'course1_step5_day_overview',
	GoodJob = 'course1_step5_good_job',
	Intention = 'course1_step5_intention',
	Activities1 = 'course1_step5_activities1',
	Activities2 = 'course1_step5_activities2',
	Activities3 = 'course1_step5_activities3',
	Activities4a = 'course1_step5_activities4a',
	Activities4b = 'course1_step5_activities4b',
	Activities5 = 'course1_step5_activities5',
	Activities6 = 'course1_step5_activities6',
	Activities7 = 'course1_step5_activities7',
	Activities8 = 'course1_step5_activities8',
	Resources1 = 'course1_step5_resources1',
	Resources2 = 'course1_step5_resources2',
	Survey = 'course1_step5_survey',
	Reflection = 'course1_step5_reflection',
}

export enum Course1Step6Screens {
	Home = 'course1_step6_home',
	DayOverview = 'course1_step6_day_overview',
	GoodJob = 'course1_step6_good_job',
	Intention = 'course1_step6_intention',
	Activities1 = 'course1_step6_activities1',
	Activities2 = 'course1_step6_activities2',
	Activities3 = 'course1_step6_activities3',
	Activities4a = 'course1_step6_activities4',
	Resources1 = 'course1_step6_resources1',
	Resources2 = 'course1_step6_resources2',
	Survey = 'course1_step6_survey',
	Reflection = 'course1_step6_reflection',
}

export enum Course1Step7Screens {
	Home = 'course1_step7_home',
	DayOverview = 'course1_step7_day_overview',
	GoodJob = 'course1_step7_good_job',
	Intention = 'course1_step7_intention',
	Activities1 = 'course1_step7_activities1',
	Activities2 = 'course1_step7_activities2',
	Activities3 = 'course1_step7_activities3',
	Activities4 = 'course1_step7_activities4',
	Resources1 = 'course1_step7_resources1',
	Resources2 = 'course1_step7_resources2',
	Survey = 'course1_step7_survey',
	Reflection = 'course1_step7_reflection',
}
